### ISSUE TITLE
Fails to load, error message

### ISSUE THREAD

**Issue by aurel-g** [LyazS/comfyui-anime-seg#4]
```

Launching ComfyUI from: /mnt/comfyui/app

Total VRAM 16073 MB, total RAM 32000 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /mnt/comfyui/app/web
Traceback (most recent call last):
  File "/mnt/comfyui/app/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/comfyui/app/custom_nodes/comfyui-anime-seg/__init__.py", line 21, in <module>
    huggingface_hub.hf_hub_download(
  File "/mnt/comfyui/env/python3.11/6f14925181260eb590f77fb6da61765a/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
TypeError: hf_hub_download() missing 1 required positional argument: 'filename'

Cannot import /mnt/comfyui/app/custom_nodes/comfyui-anime-seg module for custom nodes: hf_hub_download() missing 1 required positional argument: 'filename'

Import times for custom nodes:
   0.0 seconds: /mnt/comfyui/app/custom_nodes/websocket_image_save.py
   0.0 seconds (IMPORT FAILED): /mnt/comfyui/app/custom_nodes/comfyui-anime-seg

Starting server

To see the GUI go to: http://0.0.0.0:8080
```

**Comment by LyazS** [comment]
Download the isnetis.onnx model from [here](https://huggingface.co/skytnt/anime-seg/tree/main), and put it in the custom_nodes/comfyui-anime-seg/model directory.
Download the model manually can skip the hf_hub_download. 
Maybe I will fix the bug in furture

**Comment by aurel-g** [comment]
Yes it worked, thank you
